version: "3.7"
services:

  # api:
  #   container_name: api
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   environment:
  #     - KAFKA_BROKERS=kafka:9092
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - kafka
  #     - redis
  
  # process:
  #   container_name: process
  #   build:
  #     dockerfile: Dockerfile2
  #     context: .
  #   environment:
  #     - KAFKA_BROKERS=kafka:9092
  #   depends_on:
  #     - kafka
  #     - redis

  kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CREATE_TOPICS="rates"
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 4

  redis:
    image: redis:6.0
    ports:
      - 6379:6379

  zookeeper:
    image: docker.io/bitnami/zookeeper:3-debian-10
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes