services:
  shard_0:
    image: docker.io/bitnami/postgresql:14
    ports:
    - 8100:5432
    environment:
    - POSTGRESQL_REPLICATION_MODE=master
    - POSTGRESQL_REPLICATION_USER=replicator
    - POSTGRESQL_REPLICATION_PASSWORD=secret_password
    - POSTGRESQL_USERNAME=test
    - POSTGRESQL_PASSWORD=test
    - POSTGRESQL_DATABASE=test
    - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  replica_0:
    image: docker.io/bitnami/postgresql:14
    ports:
    - 8101:5432
    depends_on:
    - shard_0
    environment:
    - POSTGRESQL_REPLICATION_MODE=slave
    - POSTGRESQL_REPLICATION_USER=replicator
    - POSTGRESQL_REPLICATION_PASSWORD=secret_password
    - POSTGRESQL_MASTER_HOST=shard_0
    - POSTGRESQL_MASTER_PORT_NUMBER=5432
    - POSTGRESQL_PASSWORD=test
    - ALLOW_EMPTY_PASSWORD=yes
  
  shard_1:
    image: docker.io/bitnami/postgresql:14
    ports:
    - 8110:5432
    environment:
    - POSTGRESQL_REPLICATION_MODE=master
    - POSTGRESQL_REPLICATION_USER=replicator
    - POSTGRESQL_REPLICATION_PASSWORD=secret_password
    - POSTGRESQL_USERNAME=test
    - POSTGRESQL_PASSWORD=test
    - POSTGRESQL_DATABASE=test
    - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  replica_1:
    image: docker.io/bitnami/postgresql:14
    ports:
    - 8111:5432
    depends_on:
    - shard_1
    environment:
    - POSTGRESQL_REPLICATION_MODE=slave
    - POSTGRESQL_REPLICATION_USER=replicator
    - POSTGRESQL_REPLICATION_PASSWORD=secret_password
    - POSTGRESQL_MASTER_HOST=shard_1
    - POSTGRESQL_MASTER_PORT_NUMBER=5432
    - POSTGRESQL_PASSWORD=test
    - ALLOW_EMPTY_PASSWORD=yes
  shard_2:
    image: docker.io/bitnami/postgresql:14
    ports:
    - 8120:5432
    environment:
    - POSTGRESQL_REPLICATION_MODE=master
    - POSTGRESQL_REPLICATION_USER=replicator
    - POSTGRESQL_REPLICATION_PASSWORD=secret_password
    - POSTGRESQL_USERNAME=test
    - POSTGRESQL_PASSWORD=test
    - POSTGRESQL_DATABASE=test
    - ALLOW_EMPTY_PASSWORD=yes
    volumes:
        - ./init:/docker-entrypoint-initdb.d
  replica_2:
    image: docker.io/bitnami/postgresql:14
    ports:
    - 8121:5432
    depends_on:
    - shard_2
    environment:
    - POSTGRESQL_REPLICATION_MODE=slave
    - POSTGRESQL_REPLICATION_USER=replicator
    - POSTGRESQL_REPLICATION_PASSWORD=secret_password
    - POSTGRESQL_MASTER_HOST=shard_2
    - POSTGRESQL_MASTER_PORT_NUMBER=5432
    - POSTGRESQL_PASSWORD=test
    - ALLOW_EMPTY_PASSWORD=yes